version: "3.8"
services:
  mysql-dblicencias:
    image: mysql:8.1.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dblicencias
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  phpmyadmin-dblicencias:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-dblicencias
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8086:80"
    depends_on:
      - mysql-dblicencias
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge